version: '3.2'

services:
  auth-server:
    build:
      context: ./spi
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    networks:
      - pcp
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=h2
    volumes:
      - ./h2:/opt/keycloak/data/h2
  backend:
    build: ./backend
    ports:
      - "9091:8080"
    networks:
      - pcp
    environment:
      - KEYCLOAK_BASE_URL=pcp-auth-server:9090
  mockserver:
    image: ghcr.io/smocker-dev/smocker
    ports:
      - "9092:8080"
      - "9093:8081"
    networks:
      - pcp

networks:
  pcp:
    driver: bridge
